# keyword list

DEPARMENT = frozenset(['laboratorio', 'laboratories', 'laboratory',
    'laboratoire', 'institute', 'academic', 'department'])

INSTITUTE = frozenset(['college', 'university', 'universitat',
    'unversiteit', 'universita', 'universidad', 'hospital',
    "ha'pital", 'istituti', 'istituto', 'institut', 'medical center', ' pharma',
    'riuniti', 'clinic', 'school of ', 'karolinska sjukhuset',
    'national institutes of health', 'cancer center', 'bioscience institute',
    'national institute for', 'unilever research', 'national cardiovascular center',
    'centro operativo', 'animal research centre', 'nutrition research center',
    'national perinatal epidemiology unit', 'tanabe seiyaku'])

COUNTRY = (
    ('italy', 'italia'),
    ('united kingdom', 'u.k.', '\buk\b', 'uk.', 'england', ' uk', 'liverpool', 'london'),
    ('united states of america', 'u.s.a', 'u. s. a.', 'united states', 'massachusetts',
    'boston', 'howard university'),
    ('germany', 'frg', 'brd', 'f.r.g.', 'deutschland', 'engelskirchen', 'berlin',
     'hannover', 'marburg', 'mainz', 'leipzig', 'frankfurt'),
    ('japan', 'keio University', 'jikei university', 'shiga university', 'jikei university',
     'niigata university', 'sendai city', 'shiba', 'asahikawa',
     'tokyo', 'yokohama', 'osaka', 'nagoya', 'sapporo', 'kobe', 'kyoto',
     'fukuoka', 'kawasaki', 'saitama', 'hiroshima', 'sendai', 'kitakyushu',
     'chiba', 'sakai', 'hamamatsu', 'niigata', 'shizuoka', 'okayama', 'asahikawa',
     'yamaguchi', 'okayama', 'gunma', 'hyogo', 'kanazawa', 'fukui', 'tajimi',
     'komagome', 'akita', 'suita', 'kochi', 'nara medical', 'keio'),
    ('korea', 'seoul'),
    ('russia', 'moscow'),
    ('austria', 'linz', ' wien', ' graz'),
    ('israel', 'jerusalem', 'haifa'),
    ('norway', 'oslo'),
    ('finland', 'helsinki'),
    ('south africa', 'johannesburg'),
    ('france', 'paris', 'marseille', 'brest', 'limoges'),
    ('canada', 'vancouver', 'ontario', 'ottawa', 'nova scotia'),
    ('denmark', 'copenhagen'),
    ('china', 'beijing', 'pr china', 'hangzhou', 'zhejiang'),
    ('egypt', 'cairo'),
    ('poland', 'gdansk', 'krakow'),
    ('turkey', 'istanbul'),
    ('netherlands', 'utrecht', 'nijmegen'),
    ('belgium', 'belgium'),
    ('sweden', 'karlstad', 'uppsala'),
    ('australia', 'australia'),
    ('south africa', 'johannesburg', 'onderstepoort'),
    ('hungary', 'ungarn'),
    ('belgium', 'bruxelles'),
    (' india', 'chandigarh', 'hyderabad', 'delhi'),
    ('ireland', 'dublin', 'belfast'),
    ('colombia', 'bogota'),
    ('spain', ' toledo'),
    ('greece', 'athens'),
    ('new zealand', 'upper hutt'),
    ('saudi arabia', 'riyadh'),
    ('nigeria', 'ibadan'),
    ('yugoslavia', 'belgrade')
)

STATES = frozenset(['Alabama', 'Alaska', 'Arizona', 'Arkansas',
    'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida',
    'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
    'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
    'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
    'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
    'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
    'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia',
    'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Washington DC',
    ' AL', ' AK', ' AZ', ' AR', ' CA', ' CO', ' CT', ' DE', ' FL', ' GA', ' HI',
    ' ID', ' IL', ' IN', ' IA', ' KS', ' KY', ' LA', ' ME', ' MD', ' MA', ' MI',
    ' MN', ' MS', ' MO', ' MT', ' NE', ' NV', ' NH', ' NJ', ' NM', ' NY', ' NC',
    ' ND', ' OH', ' OK', ' OR', ' PA', ' RI', ' SC', ' SD', ' TN', ' TX', ' UT',
    ' VT', ' VA', ' WA', ' WV', ' WI', ' WY', ' DC',
    'San Francisco'])

UNIVERSITY_DUBLICATE = (
    ('university of california los angeles', 'ucla')
)
